services:
  postgres:
    image: postgres:18-trixie
    ports:
      - 5432:5432
    volumes:
      - pg_data_local:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_USER=postgres
  # pg-admin4:
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin


volumes:
  pg_data_local:
    driver: local
  # pgadmin-data:
  #   driver: local
