services:
  cache:
    image: valkey/valkey:8.1-trixie
    restart: always
    ports:
      - '6379:6379'
    command: valkey-server --save 20 1 --loglevel warning --requirepass admin
    volumes:
      - redis-cache:/data
volumes:
  redis-cache:
    driver: local
